// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTZFEEiPO2MjKCzUI4M2bcnF9bdfVsu8',
    appId: '1:59300085343:web:1529a3ea2500a1d8d9a5ea',
    messagingSenderId: '59300085343',
    projectId: 'chat-app-cd322',
    authDomain: 'chat-app-cd322.firebaseapp.com',
    storageBucket: 'chat-app-cd322.firebasestorage.app',
    measurementId: 'G-SN28T7BK1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNN60LNFVuAqP2Tel-AYqhzCbRNb4pd9U',
    appId: '1:59300085343:android:f925e5dade23948ed9a5ea',
    messagingSenderId: '59300085343',
    projectId: 'chat-app-cd322',
    storageBucket: 'chat-app-cd322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzcLcKw-rInsxWT8ZywuVaeGjtzPyPg6o',
    appId: '1:59300085343:ios:63105303a44abc99d9a5ea',
    messagingSenderId: '59300085343',
    projectId: 'chat-app-cd322',
    storageBucket: 'chat-app-cd322.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzcLcKw-rInsxWT8ZywuVaeGjtzPyPg6o',
    appId: '1:59300085343:ios:63105303a44abc99d9a5ea',
    messagingSenderId: '59300085343',
    projectId: 'chat-app-cd322',
    storageBucket: 'chat-app-cd322.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZTZFEEiPO2MjKCzUI4M2bcnF9bdfVsu8',
    appId: '1:59300085343:web:d83bb30add951bb6d9a5ea',
    messagingSenderId: '59300085343',
    projectId: 'chat-app-cd322',
    authDomain: 'chat-app-cd322.firebaseapp.com',
    storageBucket: 'chat-app-cd322.firebasestorage.app',
    measurementId: 'G-ZKRBDD4YQL',
  );
}
